21. **You**: hola, primero me puedes responder en español
2. **ChatGPT**: ¡Claro! Estoy aquí para ayudarte con tus preguntas sobre codificación y programación. Adelante, hazme saber en qué puedo ayudarte.
3. **You**: quiero saber donde esta el error en esta funcion  
hola("carlos", adios( nombre, ()=>{
    console.log('terminando proceso');
}))
4. **ChatGPT**: El error en la función se debe a que estás llamando a la función `adios` antes de definirla. Esto provoca un error de referencia, ya que el intérprete no sabe qué hacer con la función `adios` cuando la intentas llamar.

Para solucionar este problema, debes definir la función `adios` antes de usarla como argumento en la función `hola`. Aquí está el código corregido:

```javascript
function adios(nombre, callback) {
  console.log('Adios ' + nombre);
  callback();
}

function hola(nombre, callback) {
  console.log('Hola ' + nombre);
  callback();
}

adios(nombre, () => {
  console.log('Terminando proceso');
});

```

En este código, primero definimos la función `adios` para que esté disponible cuando la llamamos en la función `hola`. Luego, modificamos la llamada a `hola` para que primero se llame a `adios` y, finalmente, se ejecute el callback que imprime "Terminando proceso".

Es importante tener en cuenta el orden de las definiciones y llamadas a funciones para evitar errores de referencia como el que se produjo en el código original.


retomando el curso de git sabado 09/09/2023 9:19pm

//////////////////////////////////////////////////
hoy hablaremos de su vida y obra maestra.
<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Doloremque non veritatis pariatur enim dicta iure fugiat, tempora laborum laboriosam ut commodi? Impedit, facere? Sint, nisi. Earum nihil expedita cum rerum!</p>